name: Build Electron
on:
  push:
#    branches: [ master ]
    tags:
      - 'v*.*.*'

jobs:
  build:
    name: build electron app
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-latest, macos-10.15 ]
    steps:
      - name: 更新代码
        uses: actions/checkout@v2
      - name: 安装nodejs
        uses: actions/setup-node@v2-beta
      - name: 全局安装electron-builder
        run: |
          npm install electron-builder -g
      - name: 安装node_modules依赖
        run: |
          npm install
      - name: 打包window包
        if: matrix.os == 'windows-latest'
        run: |
          npm run build-win
        env:
          GH_TOKEN: ${{ secrets.REPO_TOKEN }}
      - name: 打包mac包
        if: matrix.os == 'macos-10.15'
        run: |
          npm run build-mac
        env:
          GH_TOKEN: ${{ secrets.REPO_TOKEN }}

      - name: 上传打包文件
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.os }}
          path: dist

      - name: 清理mac临时打包文件
        if: matrix.os == 'macos-10.15'
        run: |
          npx rimraf "dist/!(*.dmg)"

      - name: 清理win打包文件
        if: matrix.os == 'windows-latest'
        run: |
          npx rimraf "dist/!(*.exe)"

      - name: 发布release版本
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: "dist/**"
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
